site_name: ESP32 Club
site_url: https://docs.mekesim.com/
theme:
  name: material
  palette:
    primary: deep orange
  features:
    - search.suggest
plugins:
  - search

repo_url: https://github.com/mekesim/mekesim.github.io
repo_name: mekesim/esp32
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

google_analytics:
  - UA-40504642-3
  - auto

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      