site_name: ESP32 Cube
site_url: https://esp32cube.com/
theme:
  name: material
  palette:
    primary: deep orange
  features:
    - search.suggest
  custom_dir: overrides  
plugins:
  - search

repo_url: 
repo_name: 
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

google_analytics:
  - UA-40504642-3
  - auto

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      