site_name: Mekesim Products Document
site_url: https://docs.mekesim.com/
theme:
  name: material
  features:
    - search.suggest
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

google_analytics:
  - UA-40504642-3
  - auto

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      